#!/usr/bin/env bash
# Build and deploy home-office: the app CloudFormation stack (S3 + CloudFront +
# Lambda + HTTP API) and the static site.
#
#   ./deploy/deploy.sh
#
# Auth: locally, set AWS_PROFILE=personal-sso (after `aws sso login
# --sso-session personal-sso`). In CI (GitHub Actions), leave AWS_PROFILE unset —
# the OIDC-assumed role supplies credentials via the environment.
#
# Steps:
#   1. Build the Lambda zip with pyotp bundled.
#   2. Ensure a deploy/code bucket exists and upload the zip (content-hashed key).
#   3. Deploy the app stack (creates/updates S3, CloudFront, Lambda, API).
#   4. Generate site/config.js from the stack's ApiEndpoint output.
#   5. Sync the site to S3 and invalidate CloudFront.
#
# Stack outputs are read from CloudFormation, so nothing is hard-coded.
set -euo pipefail

REGION="${AWS_REGION:-us-east-1}"
STACK="${STACK:-home-office-app}"
PARAMETER_NAME="${PARAMETER_NAME:-/home-office/config}"

PROFILE_ARG=()
if [[ -n "${AWS_PROFILE:-}" ]]; then
  PROFILE_ARG=(--profile "$AWS_PROFILE")
fi
aws_() { aws "$@" "${PROFILE_ARG[@]}" --region "$REGION"; }

cd "$(dirname "$0")/.."
ROOT="$(pwd)"

ACCOUNT_ID="$(aws_ sts get-caller-identity --query Account --output text)"
SITE_BUCKET="home-office-${ACCOUNT_ID}"
CODE_BUCKET="home-office-deploy-${ACCOUNT_ID}"

# --- 1. Build the Lambda zip (app.py + pyotp) ----------------------------
echo "==> Building Lambda package…"
BUILD="$(mktemp -d)"
trap 'rm -rf "$BUILD"' EXIT
cp backend/app.py "$BUILD/"
python3 -m pip install -r backend/requirements.txt --target "$BUILD" --quiet \
  --only-binary=:all: 2>/dev/null || \
  python3 -m pip install -r backend/requirements.txt --target "$BUILD" --quiet

ZIP="$ROOT/backend/function.zip"
rm -f "$ZIP"
( cd "$BUILD" && zip -qr "$ZIP" . -x '*.pyc' -x '*/__pycache__/*' )

# Content-hashed key so each code change forces a Lambda update.
HASH="$(shasum -a 256 "$ZIP" | cut -c1-12)"
CODE_KEY="lambda/function-${HASH}.zip"

# --- 2. Ensure the code bucket exists and upload the zip ------------------
if ! aws_ s3api head-bucket --bucket "$CODE_BUCKET" 2>/dev/null; then
  echo "==> Creating code bucket $CODE_BUCKET…"
  # us-east-1 must NOT pass a LocationConstraint.
  if [[ "$REGION" == "us-east-1" ]]; then
    aws_ s3api create-bucket --bucket "$CODE_BUCKET" >/dev/null
  else
    aws_ s3api create-bucket --bucket "$CODE_BUCKET" \
      --create-bucket-configuration "LocationConstraint=$REGION" >/dev/null
  fi
  aws_ s3api put-public-access-block --bucket "$CODE_BUCKET" \
    --public-access-block-configuration \
    BlockPublicAcls=true,BlockPublicPolicy=true,IgnorePublicAcls=true,RestrictPublicBuckets=true
fi
echo "==> Uploading Lambda zip to s3://$CODE_BUCKET/$CODE_KEY…"
aws_ s3 cp "$ZIP" "s3://$CODE_BUCKET/$CODE_KEY" >/dev/null

# --- 3. Deploy the app stack ---------------------------------------------
echo "==> Deploying stack $STACK…"
aws_ cloudformation deploy \
  --stack-name "$STACK" \
  --template-file deploy/app.yaml \
  --capabilities CAPABILITY_IAM \
  --parameter-overrides \
    BucketName="$SITE_BUCKET" \
    ParameterName="$PARAMETER_NAME" \
    LambdaCodeBucket="$CODE_BUCKET" \
    LambdaS3Key="$CODE_KEY" \
    ${DOMAIN_NAME:+DomainName="$DOMAIN_NAME"} \
    ${HOSTED_ZONE_ID:+HostedZoneId="$HOSTED_ZONE_ID"}

# --- 4. Read outputs & generate config.js --------------------------------
read -r BUCKET DIST API URL <<<"$(aws_ cloudformation describe-stacks \
  --stack-name "$STACK" \
  --query "Stacks[0].Outputs[?OutputKey=='BucketName'||OutputKey=='DistributionId'||OutputKey=='ApiEndpoint'||OutputKey=='SiteURL'].[OutputValue]" \
  --output text | tr '\n' ' ')"
# The above returns values in template-declared order; resolve explicitly to be safe.
BUCKET="$(aws_ cloudformation describe-stacks --stack-name "$STACK" --query "Stacks[0].Outputs[?OutputKey=='BucketName'].OutputValue" --output text)"
DIST="$(aws_ cloudformation describe-stacks --stack-name "$STACK" --query "Stacks[0].Outputs[?OutputKey=='DistributionId'].OutputValue" --output text)"
API="$(aws_ cloudformation describe-stacks --stack-name "$STACK" --query "Stacks[0].Outputs[?OutputKey=='ApiEndpoint'].OutputValue" --output text)"
URL="$(aws_ cloudformation describe-stacks --stack-name "$STACK" --query "Stacks[0].Outputs[?OutputKey=='SiteURL'].OutputValue" --output text)"

echo "==> Writing site/config.js (API_BASE=$API)…"
cat > site/config.js <<EOF
// AUTO-GENERATED by deploy/deploy.sh from the CloudFormation ApiEndpoint output.
// NO secrets here — this file ships to every visitor.
window.HOME_OFFICE_CONFIG = {
  API_BASE: "$API",
};
EOF

# --- 5. Sync the site and invalidate the CDN -----------------------------
echo "==> Syncing site to s3://$BUCKET…"
# Static assets cache long; index.html and config.js always revalidate.
aws_ s3 sync site/ "s3://$BUCKET/" --delete \
  --cache-control "public,max-age=31536000,immutable" \
  --exclude "index.html" --exclude "config.js"
aws_ s3 cp site/index.html "s3://$BUCKET/index.html" \
  --cache-control "no-cache" --content-type "text/html"
aws_ s3 cp site/config.js "s3://$BUCKET/config.js" \
  --cache-control "no-cache" --content-type "application/javascript"

echo "==> Invalidating CloudFront…"
aws_ cloudfront create-invalidation --distribution-id "$DIST" --paths "/*" \
  --query "Invalidation.Id" --output text

echo "==> Done. Live at: $URL"
echo "    API: $API"
